<h1><center>Numpy - A Python Library</center></h1>

**Q1: Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.**

In [89]:
import numpy as np
og_list = [12.23, 13.32, 100, 36.32]
arr_1D = np.array(og_list)
print(arr_1D)

[ 12.23  13.32 100.    36.32]


**Q2: Create a 3x3 matrix with values ranging from 2 to 10.**

In [92]:
mat = np.arange(2,11).reshape(3,3)
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**Q3: Write a Python program to create a null vector of size 10 and update sixth value to 11.**

In [95]:
null_vector = np.zeros(10)
print(null_vector)
null_vector[5] = 11
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


**Q3: Write a Python program to create a null vector of size 10 and update sixth value to 11.**

In [98]:
null_vector = np.zeros(10)
print(null_vector)
null_vector[5] = 11
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


**Q4: Write a Python program to reverse an array (first element becomes last).**

In [101]:
og_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
print(og_array)
rev_array = np.flip(og_array)
print(rev_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


**Q5: Write a Python program to create a 2d array with 1 on the border and 0 inside.**

In [104]:
array = np.zeros((5, 5), dtype = "i")

print("Original array:")
print(array)

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print("\n1 on the border and 0 inside in the array")
print(array)


Original array:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

1 on the border and 0 inside in the array
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**Q6: Write a Python program to add a border (filled with 0's) around an existing array.**

In [107]:
original_array = np.ones((3, 3),dtype="i")

array = np.pad(original_array, pad_width=1, constant_values=0)

print("Original array:")
print(original_array)

print("\nArray with border:")
print(array)


Original array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Array with border:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


**Q7: Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.**

In [28]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("Checkerboard pattern:")
print(checkerboard)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Q8. Write a Python program to convert a list and tuple into arrays.**

In [31]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
array_from_list = np.array(lst)
print("List to array:")
print(array_from_list)

tpl = ((8, 4, 6), (1, 2, 3))
array_from_tuple = np.array(tpl)
print("\nTuple to array:")
print(array_from_tuple)


List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
 [1 2 3]]


**Q9: Write a Python program to append values to the end of an array.**

In [34]:
array = np.array([10, 20, 30])
print("Original array:")
print(array)

new_values = [40, 50, 60, 70, 80, 90]
array = np.append(array, new_values)

print("\nAfter appending values to the end of the array:")
print(array)

Original array:
[10 20 30]

After appending values to the end of the array:
[10 20 30 40 50 60 70 80 90]


**Q10. Write a Python program to find the real and imaginary parts of an array of complex numbers.**

In [37]:
complex_array = np.array([1 + 0j, 0.70710678 + 0.70710678j])

print("Original array:")
print(complex_array)

real_part = np.real(complex_array)
print("\nReal part of the array:")
print(real_part)

imag_part = np.imag(complex_array)
print("\nImaginary part of the array:")
print(imag_part)

Original array:
[1.        +0.j         0.70710678+0.70710678j]

Real part of the array:
[1.         0.70710678]

Imaginary part of the array:
[0.         0.70710678]


**Q11: Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.**

In [40]:
array = np.array([10, 20, 30], dtype=np.int64)

size = array.size
print("Size of the array:", size)

element_size = array.itemsize
print("Length of one array element in bytes:", element_size)

total_size = array.nbytes
print("Total bytes consumed by the elements of the array:", total_size)

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


**Q12. Write a Python program to find common values between two arrays.**

In [43]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

print("Array1 dimension:", array1.ndim)
print("Array2 dimension:", array2.ndim, end="\n")

print("Array1:", array1)
print("Array2:", array2)

common_values = np.intersect1d(array1, array2)
print("\nCommon values between two arrays:")
print(common_values)


Array1 dimension: 1
Array2 dimension: 1
Array1: [ 0 10 20 40 60]
Array2: [10 30 40]

Common values between two arrays:
[10 40]


**Q13: Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.**

In [47]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

print("Array1:", array1)
print("Array2:", array2)

set_difference = np.setdiff1d(array1, array2)
print("\nSet difference between two arrays:")
print(set_difference)

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]

Set difference between two arrays:
[ 0 20 60 80]


**Q14: Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.**

In [52]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

print("Array1:", array1)
print("Array2:", array2)

set_xor = np.setxor1d(array1, array2)
print("\nUnique values that are in only one (not both) of the input arrays:")
print(set_xor)

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]

Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


**Q15. Write a Python program compare two arrays using numpy.**

In [57]:
a = np.array([1, 2])
b = np.array([4, 5])

print("Array a:", a)
print("Array b:", b)

print("\na > b")
print(a > b)

print("\na >= b")
print(a >= b)

print("\na < b")
print(a < b)

print("\na <= b")
print(a <= b)


Array a: [1 2]
Array b: [4 5]

a > b
[False False]

a >= b
[False False]

a < b
[ True  True]

a <= b
[ True  True]


**Q: Write a Python program to save a NumPy array to a text file.**

In [136]:
array = np.array([[1, 2, 3], [4, 5, 6]])

np.savetxt("array.txt", array, fmt="%d")

print("Array saved to array.txt")

Array saved to array.txt


**Q16: Write a Python program to create a contiguous flattened array.**

In [70]:
array = np.array([[10, 20, 30], [20, 40, 50]])

print("Original array:")
print(array)

flattened_array = array.ravel()

print("\n New flattened array: ",flattened_array)

Original array:
[[10 20 30]
 [20 40 50]]

 New flattened array:  [10 20 30 20 40 50]


**Q17: Write a Python program to change the data type of an array.**

In [75]:
array = np.array([[2, 4, 6], [6, 8, 10]], dtype=int)

print("Original array:")
print(array)
print("\nData type of the array x is:", array.dtype)

new_array = array.astype(float)
print("\nNew Type:", new_array.dtype)
print(new_array)


Original array:
[[ 2  4  6]
 [ 6  8 10]]

Data type of the array x is: int64

New Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


**Q18: Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.**

In [80]:
array = np.eye(3)

print("Expected Output:")
print(array)

Expected Output:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Q19. Write a Python program to create an array which looks like below array.**

**<p>[0., 0., 0.],</p>**
**<p>[1., 0., 0.],</p>**
**<p>[1., 1., 0.],</p>**
**<p>[1., 1., 1.] </p>**


In [121]:
array = np.array([[0., 0., 0.],
                  [1., 0., 0.],
                  [1., 1., 0.],
                  [1., 1., 1.]])

print("Expected Output:")
print(array)

Expected Output:
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


**Q20: Write a Python program to conc-dimenatenate two dimensional arrays.**

In [128]:
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

concatenated_array = np.concatenate((array1, array2), axis=1)

print("Expected Output:")
print(concatenated_array)


Expected Output:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


**Q21: Write a Python program to make an array immutable (read-only).**

In [131]:
array = np.array([1, 2, 3, 4, 5])

array.setflags(write=False)

print("Immutable array:", array)

# Uncommenting the below line will raise an error
# array[0] = 10  
# array.append(0)

Immutable array: [1 2 3 4 5]


**Q22. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.**

In [134]:
array = np.arange(12).reshape(3, 4)

print("Original array elements:")
print(array)

new_array = array * 3

print("\nNew array elements:")
print(new_array)


Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


**Q23: Write a Python program to convert a NumPy array into Python list structure.**

In [139]:
array = np.array([[0, 1], [2, 3], [4, 5]])

print("Original array elements:")
print(array)

array_list = array.tolist()

print("\nArray to list:")
print(array_list)


Original array elements:
[[0 1]
 [2 3]
 [4 5]]

Array to list:
[[0, 1], [2, 3], [4, 5]]


**Q24: Write a Python program to convert a NumPy array into Python list structure.**

In [142]:
og_array = np.random.rand(10)

print("Original array elements:")
print(og_array)

formatted_array = np.around(array, decimals=3).tolist()

print("\nPrint array values with precision 3:")
print(formatted_array)


Original array elements:
[0.96809806 0.11673404 0.52030691 0.39865232 0.46730131 0.21174792
 0.6850212  0.66052025 0.33632472 0.43566922]

Print array values with precision 3:
[[0, 1], [2, 3], [4, 5]]


**Q25: Write a Python program to suppresses the use of scientific notation for small**

In [147]:
array = np.array([1.6e-10, 1.6, 1.2e3, 2.35e-1])

print("Original array elements:")
print(array)

np.set_printoptions(suppress=True, precision=3)

print("\nPrint array values with precision 3:")
print(array)


Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]

Print array values with precision 3:
[   0.       1.6   1200.       0.235]


In [149]:
**Q26: Write a Python program to how to add an extra column to an numpy array.**

SyntaxError: invalid syntax (1149017979.py, line 1)

In [65]:
array = np.array([[10, 20, 30], [40, 50, 60]])

extra_column = np.array([[100], [200]])

new_array = np.concatenate((array,extra_column), axis=1)

print(new_array)


[[ 10  20  30 100]
 [ 40  50  60 200]]


In [67]:
#Q27. Write a Python program to remove specific elements in a numpy array.
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:")
print(array)

indices_to_delete = [0, 3, 4]

new_array = np.delete(array, indices_to_delete )

print("\nDelete first, fourth and fifth elements:")
print(new_array)


Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
